### ISSUE TITLE
When there are two tokens that had to be MWE'ed apart

### ISSUE THREAD

**Issue by TalhaBedir** [boun-tabi/BoAT#10]
The program, for some reason, clumps together the tokens I split when there is more than one split in a sentence. For example, there are two splits: 3-4 and 11-12. When this happens, there is no tree. The tree in this screenshot belongs to a different sentence.

![Screenshot from 2020-12-08 20-29-57](https://user-images.githubusercontent.com/52924460/101522713-a91d1600-3998-11eb-90be-9793ee78e96a.png)

**Comment by gozdeberk** [comment]
Solved
