### ISSUE TITLE
Is it possible to see more proposals when I do feature correction?

### ISSUE THREAD

**Issue by TalhaBedir** [boun-tabi/BoAT#11]
While, at this point, I am quite convinced that in this project the main problem with the features is due to a lack of linguistic consensus among our team, I would also find it very helpful if there was a pop-up kind of window. When there are too many features to fix (due to misguessing the type of the word) it is really cumbersome to fix 6-7 things for one token. I would like to be able to see the second- and third-best guess of the parser, when I want to of course.

**Comment by gozdeberk** [comment]
The idea is not compatible with the parser.
