### ISSUE TITLE
Discard or fix?

### ISSUE THREAD

**Issue by TalhaBedir** [boun-tabi/BoAT#12]
![Screenshot from 2020-12-19 20-38-13](https://user-images.githubusercontent.com/52924460/102695721-29196a80-423a-11eb-8ec5-e1414c1c64cc.png)

Just like this example, there are some typos, spelling mistakes etc sometimes renders the sentence impossible to interpret. When I try to fix "alPotmek" into "alabilmek", I get the following error:

ERRORS:
[Tree number 6 on line 3 Sent news_931]: Mismatch between the text attribute and the FORM field. Form[13] is 'alabilmek' but text is 'alPotmek için DYP'den istifa ...'
[Line 27 Sent news_931]: Extra characters at the end of the text attribute, not accounted for in the FORM fields: 'alPotmek için DYP'den istifa eden Afyon Milletvekili Baki Durmaz'ı transfer etti.'

It leaves us two options:
There has to a discard option that in the end notifies us which sentences we deleted exactly and why
or there has to be a system which allows the annotator to legally fix the spelling mistake

**Comment by gozdeberk** [comment]
It is against the rules.
