### ISSUE TITLE
The error I get when I delete space between incorrectly separated copular suffixes.

### ISSUE THREAD

**Issue by TalhaBedir** [boun-tabi/BoAT#13]
![Screenshot from 2020-12-23 09-09-21](https://user-images.githubusercontent.com/52924460/102965289-9a893f80-44fe-11eb-8ff0-1432962a5602.png)

![Screenshot from 2020-12-23 09-09-28](https://user-images.githubusercontent.com/52924460/102965297-9d843000-44fe-11eb-95e9-bd001286edd1.png)

In the first screenshot, as you can see the tokens 8 and 9 are wrongly separated. When I delete space between 8 and 9 (i.e. add "SpaceAfter=No to the MISC of row 8) I get the following error as you can also see in the screenshot:

"[Line 14 Sent bio_837]: There should not be a SpaceAfter=No entry for words which are a part of a multi-word token"

Also, when this problem exists, the "dot" after is also wrongly separated in most cases. When I connect it to the preceding token via adding SpaceAfter=No, I get the same error as the one above.

**Comment by gozdeberk** [comment]
Solved
