### ISSUE TITLE
Deleting extra lines before the sentences

### ISSUE THREAD

**Issue by utkuturk** [boun-tabi/BoAT#4]
When we are working on the Turkish PUD treebank, BoAT deleted every line after the line that starts with "# text = " before every sentence. However, in other treebanks like Laz, we make use of it a lot. So, If I have a file that consists of sentences like the following, the moment I open the file it deletes the lines that includes gloss and text_en parts from the every sentence.

Is there a way to disable this?  

```
# newdoc_id = chapter_1
# paragraph_id = section_1
# sent_id = sentence_1
# text = Ma dişk’a p’t’axum.
# gloss =  I.ERG wood.NOM 1SBJ-break-TS-IMPF-PST.1SG
# text_en =  I am breaking wood.
1	Ma	Ma	PNOUN	_	Case=Erg|Number=Sing|Person=1	3	nsubj	_	_
2	dişk’a	dişk’a	NOUN	_	Case=Erg|Number=Sing	3	obj	_	_
3	p’t’axum	t’ax	VERB	_	Mood=Imp|Number[erg]=Sing|Person[erg]=1|Tense=Pst	0	root	_	SpaceAfter=No
4	.	.	PUNCT	_	_	3	punct	_	SpacesAfter=\n
```

**Comment by gozdeberk** [comment]
Solved
