### ISSUE TITLE
Punctuation problem

### ISSUE THREAD

**Issue by TalhaBedir** [boun-tabi/BoAT#9]
Tokens such as _"._ or _'._ are still bundled together. 

There is also one other problem which is at the sentence level. Sometimes, when there is a dot inside a quote, the sentence is regarded as complete. When I see such, I simply discard them out. The attached picture is simply a discarded sentence, not because of any quote but because of a dot that improperly triggered parsing.
![Screenshot from 2020-12-08 20-59-09](https://user-images.githubusercontent.com/52924460/101522435-4461bb80-3998-11eb-9ae9-5a05e3382259.png)

**Comment by gozdeberk** [comment]
This problem arises from the parser not the tool.
